## Import libraries

In [2]:
import pandas as pd
import glob
import os
import regex as re

## Read all CSV files from a folder and concatenate them

In [2]:
# use glob to get all the csv files from a folder
folder_path = "Datasets_location"
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

  
csv_list = []  
for f in csv_files:
    df = pd.read_csv(f, encoding="utf-8")
    csv_list.append(df)
    df_concat = pd.concat(csv_list)

df_concat = df_concat.reset_index().drop("index", axis=1)
df_concat = df_concat.drop("Unnamed: 0", axis=1)
df_concat

,province,id,neighbourhood,latitude,longitude,location_geo
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho..."
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò..."
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ..."
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B..."
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C..."
...,...,...,...,...,...,...
102876,Valencia,39333897,EL PERELLONET,39.28369,-0.27955,"Carrer d'Estribord, el Perellonet, Pobles del ..."
102877,Valencia,39402903,ALBORS,39.46861,-0.35141,"Col·legi Públic Angelina Carnicer, 30, Carrer ..."
102878,Valencia,41545706,LA SEU,39.47470,-0.37673,"3, Plaça de la Mare de Déu de la Pau, la Seu, ..."
102879,Valencia,40091540,EN CORTS,39.45525,-0.37380,"Barraca castillo, Carrer de Rubén Vela, En Cor..."
102880,Valencia,41617803,BENIMACLET,39.48296,-0.35622,"78, Carrer del Doctor Vicent Zaragozà, Benimac..."

In [3]:
df_concat.to_csv("Datasets_clean/all_locs_es.csv", encoding="utf-8")

## Add zip codes to the dataframe

In [4]:
for idx, address in df_concat[["location_geo"]].iterrows():
    df_concat["zip_code"] = df_concat["location_geo"].str.extract(r'\b(\d{4,5})\b')
    break

df_concat

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",08025
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",08019
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",08001
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",08002
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",08001
...,...,...,...,...,...,...,...
102876,Valencia,39333897,EL PERELLONET,39.28369,-0.27955,"Carrer d'Estribord, el Perellonet, Pobles del ...",46420
102877,Valencia,39402903,ALBORS,39.46861,-0.35141,"Col·legi Públic Angelina Carnicer, 30, Carrer ...",46021
102878,Valencia,41545706,LA SEU,39.47470,-0.37673,"3, Plaça de la Mare de Déu de la Pau, la Seu, ...",46001
102879,Valencia,40091540,EN CORTS,39.45525,-0.37380,"Barraca castillo, Carrer de Rubén Vela, En Cor...",46006
102880,Valencia,41617803,BENIMACLET,39.48296,-0.35622,"78, Carrer del Doctor Vicent Zaragozà, Benimac...",46020

In [5]:
df_concat["zip_code"].nunique()

1180

In [6]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102881 entries, 0 to 102880
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   province       102881 non-null  object
 1   id             102881 non-null  int64
 2   neighbourhood  102881 non-null  object
 3   latitude       102881 non-null  float64
 4   longitude      102881 non-null  float64
 5   location_geo   102881 non-null  object
 6   zip_code       101621 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.5+ MB

In [7]:
df_concat[df_concat["zip_code"].isnull()]

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code
2145,Valencia,42531886,ARRANCAPINS,39.460820,-0.382410,"Arrancapins, Extramurs, València, Comarca de V...",NaN
2590,Valencia,47828175,LA RAIOSA,39.459420,-0.386710,"la Raïosa, Jesús, València, Comarca de Valènci...",NaN
2660,Valencia,49697009,LA XEREA,39.474700,-0.369920,"la Xerea, Ciutat Vella, València, Comarca de V...",NaN
2749,Valencia,50219427,LA SEU,39.478428,-0.375507,"Plaça dels Cecs, la Seu, Ciutat Vella, Valènci...",NaN
2936,Valencia,50547834,L'ILLA PERDUDA,39.470790,-0.339620,"Plaça del Pintor Anglada, l'Illa Perduda, Algi...",NaN
...,...,...,...,...,...,...,...
102068,Valencia,28100509,L'ILLA PERDUDA,39.470350,-0.339980,"Plaça del Pintor Anglada, l'Illa Perduda, Algi...",NaN
102589,Valencia,34596349,EL CARME,39.479560,-0.377310,"Plaça de l'Autor, el Carme, Ciutat Vella, Valè...",NaN
102603,Valencia,36510524,LA SEU,39.476280,-0.374430,"Plaça de Dècim Juni Brut Cònsol Romà, la Seu, ...",NaN
102732,Valencia,37519796,CABANYAL-CANYAMELAR,39.469050,-0.330940,"Plaça del Doctor Llorenç de la Flor, Canyamela...",NaN
102864,Valencia,41497666,EL BOTANIC,39.475970,-0.384610,"Plaça de Maria Beneyto Escriptora, el Botànic,...",NaN

In [8]:
# convert all elements in zip_code column to integer (in-place), so we can merge them later with other table

df_concat.loc[df_concat["zip_code"].notnull(), "zip_code"] = df_concat.loc[df_concat["zip_code"].notnull(), "zip_code"].astype(int)

In [9]:
# replace NaN elements in zip_code column to 0, so the dtype of this column can become integer

df_concat["zip_code"].fillna(0, inplace=True)

In [10]:
# dtype of "zip_code" column is now integer

df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102881 entries, 0 to 102880
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   province       102881 non-null  object
 1   id             102881 non-null  int64
 2   neighbourhood  102881 non-null  object
 3   latitude       102881 non-null  float64
 4   longitude      102881 non-null  float64
 5   location_geo   102881 non-null  object
 6   zip_code       102881 non-null  int64
dtypes: float64(2), int64(2), object(3)
memory usage: 5.5+ MB

In [11]:
df_concat.to_csv("Datasets_clean/all_locs_zipcode_es.csv", encoding="utf-8")

## Merge "df_concat" with "codigos_postales.csv" to get municipalities

In [12]:
zip_codes = pd.read_csv("Datasets_clean/codigos_postales.csv", encoding="utf-8")
zip_codes

,codigo_postal,municipio_id,municipio_nombre,codigo_unidad_poblacional,entidad_singular_nombre,nucleo_nombre
0,43,43110,"Pobla de Massaluca, La",1799,Pobla de Massaluca (La),*Diseminado*
1,85,49064,Fariza,5699,Palazuelo de Sayago,*Diseminado*
2,633,26005,Albelda de Iregua,1799,Albelda de Iregua,*Diseminado*
3,1001,1059,Vitoria-Gasteiz,63501,Vitoria-Gasteiz,Vitoria-Gasteiz
4,1002,1059,Vitoria-Gasteiz,63501,Vitoria-Gasteiz,Vitoria-Gasteiz
...,...,...,...,...,...,...
77615,52002,52001,Melilla,3801,Melilla,Melilla
77616,52003,52001,Melilla,3801,Melilla,Melilla
77617,52004,52001,Melilla,3801,Melilla,Melilla
77618,52005,52001,Melilla,3801,Melilla,Melilla
77619,52006,52001,Melilla,3801,Melilla,Melilla

In [14]:
zip_codes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77620 entries, 0 to 77619
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   codigo_postal              77620 non-null  int64
 1   municipio_id               77620 non-null  int64
 2   municipio_nombre           77620 non-null  object
 3   codigo_unidad_poblacional  77620 non-null  int64
 4   entidad_singular_nombre    77620 non-null  object
 5   nucleo_nombre              77620 non-null  object
dtypes: int64(3), object(3)
memory usage: 3.6+ MB

In [15]:
zip_codes = zip_codes.rename({"codigo_postal" : "zip_code"}, axis=1)
zip_codes = zip_codes.loc[:, "zip_code":"codigo_unidad_poblacional"]
zip_codes = zip_codes[["zip_code", "municipio_id", "codigo_unidad_poblacional", "municipio_nombre"]]
zip_codes

,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
0,43,43110,1799,"Pobla de Massaluca, La"
1,85,49064,5699,Fariza
2,633,26005,1799,Albelda de Iregua
3,1001,1059,63501,Vitoria-Gasteiz
4,1002,1059,63501,Vitoria-Gasteiz
...,...,...,...,...
77615,52002,52001,3801,Melilla
77616,52003,52001,3801,Melilla
77617,52004,52001,3801,Melilla
77618,52005,52001,3801,Melilla
77619,52006,52001,3801,Melilla

In [16]:
complete_address = pd.merge(df_concat, zip_codes, on="zip_code", how="left")
complete_address = complete_address.drop_duplicates(subset="id", keep="first")
complete_address.head()

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,8019.0,1701.0,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,8019.0,1701.0,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,8019.0,1701.0,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,8019.0,1701.0,Barcelona
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,8019.0,1701.0,Barcelona

In [17]:
complete_address.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102881 entries, 0 to 382760
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   province                   102881 non-null  object
 1   id                         102881 non-null  int64
 2   neighbourhood              102881 non-null  object
 3   latitude                   102881 non-null  float64
 4   longitude                  102881 non-null  float64
 5   location_geo               102881 non-null  object
 6   zip_code                   102881 non-null  int64
 7   municipio_id               98394 non-null   float64
 8   codigo_unidad_poblacional  98394 non-null   float64
 9   municipio_nombre           98394 non-null   object
dtypes: float64(4), int64(2), object(4)
memory usage: 8.6+ MB

## Merge "complete_address" with the "provinces" table

In [18]:
provinces = pd.read_html("https://www.ine.es/daco/daco42/codmun/cod_ccaa_provincia.htm")
provinces = provinces[0]
provinces = provinces[["Comunidad Autónoma", "Provincia"]]
provinces

             Comunidad Autónoma               Provincia
0                     Andalucía                 Almería
1                     Andalucía                   Cádiz
2                     Andalucía                 Córdoba
3                     Andalucía                 Granada
4                     Andalucía                  Huelva
5                     Andalucía                    Jaén
6                     Andalucía                  Málaga
7                     Andalucía                 Sevilla
8                        Aragón                  Huesca
9                        Aragón                  Teruel
10                       Aragón                Zaragoza
11      Asturias, Principado de                Asturias
12               Balears, Illes          Balears, Illes
13                     Canarias             Palmas, Las
14                     Canarias  Santa Cruz de Tenerife
15                    Cantabria               Cantabria
16              Castilla y León                   Ávila
17              Castilla y León                  Burgos
18              Castilla y León                    León
19              Castilla y León                Palencia
20              Castilla y León               Salamanca
21              Castilla y León                 Segovia
22              Castilla y León                   Soria
23              Castilla y León              Valladolid
24              Castilla y León                  Zamora
25           Castilla-La Mancha                Albacete
26           Castilla-La Mancha             Ciudad Real
27           Castilla-La Mancha                  Cuenca
28           Castilla-La Mancha             Guadalajara
29           Castilla-La Mancha                  Toledo
30                     Cataluña               Barcelona
31                     Cataluña                  Girona
32                     Cataluña                  Lleida
33                     Cataluña               Tarragona
34         Comunitat Valenciana        Alicante/Alacant
35         Comunitat Valenciana      Castellón/Castelló
36         Comunitat Valenciana       Valencia/València
37                  Extremadura                 Badajoz
38                  Extremadura                 Cáceres
39                      Galicia               Coruña, A
40                      Galicia                    Lugo
41                      Galicia                 Ourense
42                      Galicia              Pontevedra
43         Madrid, Comunidad de                  Madrid
44            Murcia, Región de                  Murcia
45  Navarra, Comunidad Foral de                 Navarra
46                   País Vasco             Araba/Álava
47                   País Vasco                 Bizkaia
48                   País Vasco                Gipuzkoa
49                    Rioja, La               Rioja, La
50          Ciudades Autónomas:                     NaN
51                        Ceuta                   Ceuta
52                      Melilla                 Melilla

In [19]:
provinces.to_csv("Datasets_clean/provinces.csv", encoding="utf-8")

## Total property IDs is 102881 which is correct, but there are 4487 missing values in the "municipio_nombre". That's because:
- the bot took street or house number, instead of zip code  --> workaround: split address by comma and take the -2 position from the list
- OR there are no zip codes provided in the "complete_address" taken from Geopy Nominatim --> workaround: the zip codes are used to identify the cities, provinces and states for groupby purpose. Thus, for those that don't have zip codes, please use city name or neighbourhood name.

In [20]:
complete_address[complete_address["municipio_nombre"].isna()]

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
339,Barcelona,682808,la Dreta de l'Eixample,41.39362,2.16868,"Hotel Catalonia Eixample 1864, 60, Carrer de R...",1864,NaN,NaN,NaN
659,Barcelona,1327003,el Poble Sec,41.37390,2.16347,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",1968,NaN,NaN,NaN
1554,Barcelona,43492389,el Poble Sec,41.37405,2.16364,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",1968,NaN,NaN,NaN
1815,Barcelona,44030374,el Barri Gòtic,41.38417,2.17200,"Living Barcelona 1925, Plaça de la Vila de Mad...",1925,NaN,NaN,NaN
1817,Barcelona,44585025,"Sant Pere, Santa Caterina i la Ribera",41.38248,2.18403,Monument Barcelona al general Moragues. 1672 –...,1672,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
382513,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",1234,NaN,NaN,NaN
382538,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN
382547,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",1210,NaN,NaN,NaN
382596,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",1356,NaN,NaN,NaN
382739,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN

### Create a new variable called "df_concat2" to save the 4487 missing municipality names. Now the column "zip_code" in this new variable contain the incorrect values only

In [21]:
df_concat2 = complete_address[complete_address["municipio_nombre"].isna()]
df_concat2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
339,Barcelona,682808,la Dreta de l'Eixample,41.39362,2.16868,"Hotel Catalonia Eixample 1864, 60, Carrer de R...",1864,NaN,NaN,NaN
659,Barcelona,1327003,el Poble Sec,41.37390,2.16347,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",1968,NaN,NaN,NaN
1554,Barcelona,43492389,el Poble Sec,41.37405,2.16364,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",1968,NaN,NaN,NaN
1815,Barcelona,44030374,el Barri Gòtic,41.38417,2.17200,"Living Barcelona 1925, Plaça de la Vila de Mad...",1925,NaN,NaN,NaN
1817,Barcelona,44585025,"Sant Pere, Santa Caterina i la Ribera",41.38248,2.18403,Monument Barcelona al general Moragues. 1672 –...,1672,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
382513,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",1234,NaN,NaN,NaN
382538,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN
382547,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",1210,NaN,NaN,NaN
382596,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",1356,NaN,NaN,NaN
382739,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN

In [22]:
# Take the correct zip codes from the "location_geo" column again

zipcode_list = []
for i in df_concat2["location_geo"]:
    i = i.split(",")[-2]
    i = i.strip()
    if len(i) == 4 or len(i) == 5:
        i = int(i)
    else:
        i = 0
    zipcode_list.append(i)
zipcode_list

[8001,
 8004,
 8004,
 8001,
 8001,
 16015,
 0,
 46022,
 46022,
 46022,
 46012,
 16015,
 46023,
 0,
 46022,
 0,
 0,
 46024,
 16015,
 0,
 46022,
 46011,
 0,
 46024,
 46024,
 46022,
 16015,
 0,
 46024,
 16015,
 46024,
 0,
 16015,
 0,
 46023,
 0,
 0,
 46024,
 46011,
 0,
 0,
 0,
 16015,
 46011,
 0,
 0,
 46025,
 46020,
 0,
 16015,
 0,
 16015,
 0,
 46011,
 46020,
 46021,
 46011,
 46023,
 0,
 0,
 46024,
 46021,
 46020,
 16015,
 46011,
 46024,
 46011,
 46015,
 0,
 0,
 16015,
 0,
 0,
 0,
 0,
 0,
 46006,
 16015,
 8001,
 8001,
 8001,
 8001,
 8020,
 8001,
 8001,
 8001,
 8001,
 48395,
 0,
 48310,
 1193,
 1193,
 0,
 48071,
 0,
 1193,
 1232,
 48310,
 0,
 20300,
 1308,
 1232,
 48360,
 48620,
 20130,
 20130,
 1170,
 20300,
 0,
 0,
 48148,
 48310,
 48310,
 20809,
 20550,
 48360,
 0,
 20130,
 1307,
 48289,
 48141,
 48287,
 1307,
 48620,
 48287,
 20130,
 48314,
 48125,
 20130,
 0,
 0,
 0,
 0,
 20300,
 48360,
 48380,
 0,
 48370,
 48071,
 48310,
 20269,
 48148,
 0,
 1232,
 0,
 0,
 48141,
 48311,
 48125,
 20269,
 20759,
 20269,
 48370,
 0,
 0,
 0,
 1427,
 48071,
 48071,
 1430,
 1430,
 1430,
 20870,
 1449,
 0,
 0,
 0,
 0,
 0,
 0,
 1118,
 20300,
 48395,
 0,
 48287,
 48317,
 48317,
 1232,
 20267,
 48460,
 0,
 48291,
 48382,
 0,
 20267,
 48350,
 0,
 0,
 0,
 0,
 48287,
 0,
 48287,
 48148,
 1232,
 48148,
 0,
 64700,
 48383,
 48620,
 48071,
 48071,
 48410,
 0,
 0,
 48620,
 0,
 48071,
 48350,
 48148,
 0,
 48370,
 48370,
 48370,
 48370,
 48370,
 48370,
 48370,
 48317,
 48317,
 0,
 0,
 0,
 0,
 0,
 0,
 20180,
 48317,
 48317,
 48317,
 20808,
 1232,
 0,
 48395,
 48317,
 20120,
 48289,
 48141,
 48148,
 48148,
 48620,
 48289,
 20800,
 48310,
 48710,
 1479,
 48710,
 20300,
 48278,
 48710,
 48071,
 48278,
 0,
 0,
 0,
 0,
 48395,
 0,
 0,
 20720,
 0,
 20259,
 48314,
 0,
 0,
 48289,
 48289,
 48289,
 48289,
 48289,
 48310,
 48310,
 48310,
 48310,
 20130,
 48313,
 1232,
 0,
 48287,
 0,
 48620,
 48289,
 1468,
 48360,
 48620,
 48620,
 20300,
 0,
 48700,
 48289,
 48190,
 48071,
 48071,
 48395,
 1308,
 20809,
 48071,
 48148,
 48620,
 20300,
 20300,
 20300,
 1232,
 48392,
 0,
 48314,
 0,
 0,
 1232,
 48360,
 0,
 0,
 48620,
 20829,
 0,
 48190,
 20738,
 20738,
 0,
 20730,
 20759,
 0,
 0,
 48620,
 48393,
 48317,
 48315,
 48620,
 48620,
 48620,
 48620,
 48620,
 48289,
 20800,
 48393,
 64700,
 48394,
 48287,
 48620,
 48287,
 48287,
 0,
 0,
 1468,
 1232,
 0,
 0,
 48620,
 1308,
 1306,
 20490,
 20490,
 0,
 0,
 0,
 0,
 0,
 48141,
 48915,
 0,
 48350,
 0,
 48071,
 48071,
 0,
 20300,
 0,
 48130,
 48620,
 0,
 48071,
 0,
 48071,
 48071,
 48071,
 0,
 1450,
 1232,
 48620,
 40102,
 48620,
 1232,
 1232,
 1232,
 1232,
 1232,
 1232,
 48289,
 48289,
 48016,
 48016,
 48314,
 1232,
 48287,
 48350,
 48350,
 0,
 0,
 48190,
 48071,
 48350,
 48350,
 48350,
 0,
 48620,
 20740,
 48392,
 48620,
 48620,
 48620,
 48620,
 48620,
 48620,
 48700,
 48195,
 0,
 20809,
 20740,
 20870,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 20180,
 48380,
 1450,
 1193,
 0,
 0,
 48620,
 1232,
 48395,
 48287,
 48287,
 48820,
 48071,
 1449,
 0,
 48289,
 0,
 17867,
 17845,
 17850,
 17121,
 17845,
 0,
 17185,
 17741,
 0,
 0,
 0,
 0,
 0,
 17867,
 0,
 17741,
 17462,
 17845,
 17845,
 17845,
 17845,
 11748,
 17867,
 17222,
 0,
 67551,
 17867,
 17867,
 17867,
 0,
 67551,
 0,
 17869,
 0,
 67551,
 17832,
 17947,
 0,
 0,
 17222,
 17115,
 17854,
 17213,
 17841,
 0,
 67551,
 17121,
 67551,
 0,
 17855,
 17867,
 17136,
 17115,
 67551,
 0,
 17845,
 17845,
 17470,
 17470,
 0,
 17222,
 67551,
 0,
 67551,
 67551,
 0,
 0,
 67551,
 0,
 17761,
 17781,
 17534,
 17534,
 0,
 67551,
 67551,
 0,
 0,
 67551,
 0,
 0,
 67551,
 0,
 0,
 0,
 0,
 0,
 17534,
 0,
 0,
 0,
 0,
 0,
 17255,
 17587,
 0,
 17587,
 67551,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 17222,
 0,
 0,
 17850,
 17255,
 17222,
 17222,
 17587,
 0,
 17841,
 67551,
 17222,
 0,
 0,
 17538,
 17587,
 0,
 17489,
 17222,
 0,
 0,
 17869,
 17856,
 17115,
 17222,
 17222,
 17222,
 0,
 17212,
 17212,
 17587,
 67551,
 67551,
 17536,
 0,
 17536,
 17533,
 17520,
 17212,
 0,
 17136,
 17741,
 17004,
 67551,
 17533,
 0,
 17212,
 0,
 17533,
 17533,
 17533,
 0,
 17489,
 17746,
 17452,
 17222,
 17533,
 17947,
 0,
 17222,
 17452,
 17116,
 17587,
 17841,
 0,
 17534,
 0,
 17144,
 0,
 0,
 17222,
 0,
 8001,
 8001,
 8001,
 17404,
 0,
 67551,
 17947,
 17855,
 0,
 17222,
 17587,
 17222,
 17867,
 17741,
 0,
 17746,
 17867,
 67551,
 17199,
 0,
 17856,
 17469,
 17121,
 67551,
 17222,
 0,
 17587,
 0,
 17222,
 17474,
 17587,
 67551,
 11748,
 17115,
 17587,
 0,
 0,
 0,
 17587,
 67551,
 17144,
 17841,
 17741,
 17533,
 17533,
 17830,
 17845,
 0,
 17867,
 17867,
 17845,
 17401,
 17841,
 17533,
 17841,
 0,
 0,
 17587,
 17405,
 17248,
 17213,
 0,
 0,
 0,
 0,
 67551,
 17222,
 17222,
 0,
 0,
 0,
 17121,
 67551,
 67551,
 67551,
 67551,
 67551,
 67551,
 67551,
 67551,
 67551,
 17947,
 0,
 0,
 17474,
 0,
 0,
 0,
 67551,
 0,
 17485,
 0,
 17474,
 17199,
 0,
 17222,
 17222,
 0,
 17841,
 0,
 17468,
 17855,
 17468,
 0,
 0,
 17474,
 0,
 17533,
 17470,
 0,
 17867,
 17222,
 17222,
 0,
 0,
 0,
 0,
 0,
 17470,
 17222,
 17730,
 17470,
 17741,
 0,
 17741,
 17222,
 0,
 0,
 17222,
 17222,
 0,
 67551,
 17469,
 0,
 17462,
 17462,
 0,
 0,
 0,
 0,
 17469,
 0,
 0,
 17213,
 17746,
 17222,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 17222,
 17587,
 17255,
 17486,
 17587,
 17474,
 0,
 17222,
 17834,
 17854,
 17001,
 17746,
 0,
 0,
 17587,
 0,
 17867,
 17534,
 0,
 0,
 0,
 17854,
 0,
 17222,
 17115,
 0,
 0,
 0,
 0,
 0,
 17856,
 67551,
 0,
 0,
 17752,
 17489,
 17144,
 17486,
 17043,
 0,
 0,
 17869,
 17222,
 0,
 0,
 17469,
 0,
 17115,
 17222,
 17211,
 17222,
 17144,
 17830,
 17222,
 17222,
 67551,
 0,
 0,
 0,
 0,
 17534,
 17222,
 17222,
 17533,
 17222,
 17533,
 17830,
 0,
 0,
 0,
 0,
 0,
 17222,
 0,
 67551,
 17401,
 17474,
 17587,
 17137,
 17587,
 0,
 17222,
 17222,
 0,
 17587,
 8001,
 8001,
 67551,
 0,
 17222,
 17120,
 67551,
 0,
 0,
 0,
 0,
 0,
 17587,
 17520,
 17121,
 0,
 17222,
 17534,
 17222,
 17587,
 17841,
 0,
 0,
 0,
 0,
 28071,
 28071,
 28071,
 28071,
 28071,
 28071,
 29039,
 28071,
 28004,
 29039,
 28071,
 29039,
 29039,
 28929,
 0,
 23043,
 28071,
 28012,
 29039,
 28071,
 28071,
 0,
 28071,
 29039,
 28929,
 0,
 0,
 28071,
 29039,
 23043,
 23043,
 28071,
 28929,
 0,
 29039,
 28071,
 28071,
 28929,
 29039,
 0,
 0,
 29039,
 28004,
 28071,
 29039,
 28071,
 29039,
 0,
 28071,
 29039,
 28071,
 23043,
 28071,
 29039,
 29039,
 28929,
 28093,
 28929,
 28929,
 28071,
 28929,
 28929,
 29039,
 29039,
 29039,
 29039,
 28929,
 28929,
 28929,
 29039,
 28071,
 0,
 28071,
 28012,
 28071,
 28929,
 0,
 28071,
 29039,
 29039,
 0,
 0,
 29039,
 28013,
 0,
 0,
 0,
 28929,
 28071,
 28071,
 28071,
 29039,
 28929,
 0,
 29039,
 0,
 29039,
 29039,
 0,
 23043,
 8001,
 0,
 8001,
 29039,
 28071,
 28929,
 29039,
 28001,
 28929,
 0,
 23043,
 0,
 ...]

In [23]:
# Replace the incorrect zip codes with the correct ones

df_concat2["zip_code"] = zipcode_list
df_concat2

C:\Users\Selvie\AppData\Local\Temp\ipykernel_34796\387060098.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_concat2["zip_code"] = zipcode_list

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
339,Barcelona,682808,la Dreta de l'Eixample,41.39362,2.16868,"Hotel Catalonia Eixample 1864, 60, Carrer de R...",8001,NaN,NaN,NaN
659,Barcelona,1327003,el Poble Sec,41.37390,2.16347,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",8004,NaN,NaN,NaN
1554,Barcelona,43492389,el Poble Sec,41.37405,2.16364,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",8004,NaN,NaN,NaN
1815,Barcelona,44030374,el Barri Gòtic,41.38417,2.17200,"Living Barcelona 1925, Plaça de la Vila de Mad...",8001,NaN,NaN,NaN
1817,Barcelona,44585025,"Sant Pere, Santa Caterina i la Ribera",41.38248,2.18403,Monument Barcelona al general Moragues. 1672 –...,8001,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
382513,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",46023,NaN,NaN,NaN
382538,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN
382547,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",46021,NaN,NaN,NaN
382596,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",46022,NaN,NaN,NaN
382739,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN

In [24]:
# Merge again "df_concat2" with "zip_codes" to get "municipio_nombre"

complete_address2 = pd.merge(df_concat2, zip_codes, on="zip_code", how="left")
complete_address2 = complete_address2.drop_duplicates(subset="id", keep="first")
complete_address2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id_x,codigo_unidad_poblacional_x,municipio_nombre_x,municipio_id_y,codigo_unidad_poblacional_y,municipio_nombre_y
0,Barcelona,682808,la Dreta de l'Eixample,41.39362,2.16868,"Hotel Catalonia Eixample 1864, 60, Carrer de R...",8001,NaN,NaN,NaN,8019.0,1701.0,Barcelona
1,Barcelona,1327003,el Poble Sec,41.37390,2.16347,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",8004,NaN,NaN,NaN,8019.0,1701.0,Barcelona
2,Barcelona,43492389,el Poble Sec,41.37405,2.16364,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",8004,NaN,NaN,NaN,8019.0,1701.0,Barcelona
3,Barcelona,44030374,el Barri Gòtic,41.38417,2.17200,"Living Barcelona 1925, Plaça de la Vila de Mad...",8001,NaN,NaN,NaN,8019.0,1701.0,Barcelona
4,Barcelona,44585025,"Sant Pere, Santa Caterina i la Ribera",41.38248,2.18403,Monument Barcelona al general Moragues. 1672 –...,8001,NaN,NaN,NaN,8019.0,1701.0,Barcelona
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8261,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",46023,NaN,NaN,NaN,46250.0,14101.0,Valencia
8262,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN,NaN,NaN,NaN
8263,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",46021,NaN,NaN,NaN,46250.0,14101.0,Valencia
8264,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",46022,NaN,NaN,NaN,46250.0,14101.0,Valencia
8265,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
complete_address2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4487 entries, 0 to 8265
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   province                     4487 non-null   object
 1   id                           4487 non-null   int64
 2   neighbourhood                4487 non-null   object
 3   latitude                     4487 non-null   float64
 4   longitude                    4487 non-null   float64
 5   location_geo                 4487 non-null   object
 6   zip_code                     4487 non-null   int64
 7   municipio_id_x               0 non-null      float64
 8   codigo_unidad_poblacional_x  0 non-null      float64
 9   municipio_nombre_x           0 non-null      object
 10  municipio_id_y               968 non-null    float64
 11  codigo_unidad_poblacional_y  968 non-null    float64
 12  municipio_nombre_y           968 non-null    object
dtypes: float64(6), int64(2), object(5)
memory usage: 490.8+ KB

In [26]:
complete_address2 = complete_address2.drop(["municipio_id_x", "codigo_unidad_poblacional_x", "municipio_nombre_x"], axis=1)
complete_address2 = complete_address2.rename({"municipio_id_y" : "municipio_id",
                                              "codigo_unidad_poblacional_y" : "codigo_unidad_poblacional",
                                              "municipio_nombre_y" : "municipio_nombre"}, axis=1)
complete_address2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
0,Barcelona,682808,la Dreta de l'Eixample,41.39362,2.16868,"Hotel Catalonia Eixample 1864, 60, Carrer de R...",8001,8019.0,1701.0,Barcelona
1,Barcelona,1327003,el Poble Sec,41.37390,2.16347,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",8004,8019.0,1701.0,Barcelona
2,Barcelona,43492389,el Poble Sec,41.37405,2.16364,"Sasha Bar 1968, 18, Carrer de Margarit, el Pob...",8004,8019.0,1701.0,Barcelona
3,Barcelona,44030374,el Barri Gòtic,41.38417,2.17200,"Living Barcelona 1925, Plaça de la Vila de Mad...",8001,8019.0,1701.0,Barcelona
4,Barcelona,44585025,"Sant Pere, Santa Caterina i la Ribera",41.38248,2.18403,Monument Barcelona al general Moragues. 1672 –...,8001,8019.0,1701.0,Barcelona
...,...,...,...,...,...,...,...,...,...,...
8261,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",46023,46250.0,14101.0,Valencia
8262,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN
8263,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",46021,46250.0,14101.0,Valencia
8264,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",46022,46250.0,14101.0,Valencia
8265,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN

### Append "complete_address" and "complete_address2"

In [27]:
complete_address.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102881 entries, 0 to 382760
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   province                   102881 non-null  object
 1   id                         102881 non-null  int64
 2   neighbourhood              102881 non-null  object
 3   latitude                   102881 non-null  float64
 4   longitude                  102881 non-null  float64
 5   location_geo               102881 non-null  object
 6   zip_code                   102881 non-null  int64
 7   municipio_id               98394 non-null   float64
 8   codigo_unidad_poblacional  98394 non-null   float64
 9   municipio_nombre           98394 non-null   object
dtypes: float64(4), int64(2), object(4)
memory usage: 8.6+ MB

In [28]:
complete_address2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4487 entries, 0 to 8265
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   province                   4487 non-null   object
 1   id                         4487 non-null   int64
 2   neighbourhood              4487 non-null   object
 3   latitude                   4487 non-null   float64
 4   longitude                  4487 non-null   float64
 5   location_geo               4487 non-null   object
 6   zip_code                   4487 non-null   int64
 7   municipio_id               968 non-null    float64
 8   codigo_unidad_poblacional  968 non-null    float64
 9   municipio_nombre           968 non-null    object
dtypes: float64(4), int64(2), object(4)
memory usage: 385.6+ KB

In [29]:
complete_address_1_2 = pd.concat([complete_address, complete_address2], axis=0)
complete_address_1_2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,8019.0,1701.0,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,8019.0,1701.0,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,8019.0,1701.0,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,8019.0,1701.0,Barcelona
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,8019.0,1701.0,Barcelona
...,...,...,...,...,...,...,...,...,...,...
8261,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",46023,46250.0,14101.0,Valencia
8262,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN
8263,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",46021,46250.0,14101.0,Valencia
8264,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",46022,46250.0,14101.0,Valencia
8265,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN

In [30]:
complete_address_1_2 = complete_address_1_2.drop_duplicates(subset="id", keep="last")
complete_address_1_2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_id,codigo_unidad_poblacional,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,8019.0,1701.0,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,8019.0,1701.0,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,8019.0,1701.0,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,8019.0,1701.0,Barcelona
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,8019.0,1701.0,Barcelona
...,...,...,...,...,...,...,...,...,...,...
8261,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",46023,46250.0,14101.0,Valencia
8262,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN,NaN,NaN
8263,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",46021,46250.0,14101.0,Valencia
8264,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",46022,46250.0,14101.0,Valencia
8265,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN,NaN,NaN

In [31]:
complete_address_1_2 = complete_address_1_2.reset_index()
complete_address_1_2 = complete_address_1_2.drop("index", axis=1)

In [32]:
complete_address_1_2 = complete_address_1_2.drop(["municipio_id", "codigo_unidad_poblacional"], axis=1)

In [33]:
complete_address_1_2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,Barcelona
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,Barcelona
...,...,...,...,...,...,...,...,...
102876,Valencia,35443318,LA CREU DEL GRAU,39.46055,-0.34528,"1234, Carrer de Carolina Álvarez, la Creu del ...",46023,Valencia
102877,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN
102878,Valencia,35574391,AIORA,39.46811,-0.34388,"1210, Carrer dels Sants Just i Pastor, Aiora, ...",46021,Valencia
102879,Valencia,35832256,LA VEGA BAIXA,39.47818,-0.34958,"1356, Carrer d'Albalat dels Tarongers, la Carr...",46022,Valencia
102880,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN

### Check again how many rows don't have the municipality names

In [34]:
complete_address_1_2[complete_address_1_2["municipio_nombre"].isna()]

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98399,Valencia,39682770,LA PETXINA,39.47706,-0.39169,"Passeig de la Petxina, la Petxina, Extramurs, ...",16015,NaN
98400,Valencia,42531886,ARRANCAPINS,39.46082,-0.38241,"Arrancapins, Extramurs, València, Comarca de V...",0,NaN
98405,Valencia,48050433,LA PETXINA,39.47682,-0.39346,"Estadi del Túria, Avinguda de Campanar, Campan...",16015,NaN
98407,Valencia,47828175,LA RAIOSA,39.45942,-0.38671,"la Raïosa, Jesús, València, Comarca de Valènci...",0,NaN
98409,Valencia,49697009,LA XEREA,39.47470,-0.36992,"la Xerea, Ciutat Vella, València, Comarca de V...",0,NaN
...,...,...,...,...,...,...,...,...
102872,Valencia,34596349,EL CARME,39.47956,-0.37731,"Plaça de l'Autor, el Carme, Ciutat Vella, Valè...",0,NaN
102873,Valencia,36510524,LA SEU,39.47628,-0.37443,"Plaça de Dècim Juni Brut Cònsol Romà, la Seu, ...",0,NaN
102874,Valencia,37206278,EL CALVARI,39.48659,-0.39257,"Carrer de l'Esperantista Hernández Lahuerta, e...",16015,NaN
102877,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN
102880,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN

In [35]:
# Seems that the following zip codes do not match any of the zip codes in the zip_codes table

complete_address_1_2[complete_address_1_2["municipio_nombre"].isna()]["zip_code"].unique()

array([16015,     0, 48071,  1232, 20300, 48148, 48125, 20759, 48317,
       64700, 20738, 48915, 40102, 48016, 17845, 11748, 17222, 67551,
       17947, 17115, 17841, 17587, 17533, 17043, 28071, 29039, 28929,
       23043, 28093, 28334, 28820, 29080, 29104, 29071,  7408,  7410,
       70712,  7121,  7122,  7060,  7000,  7602, 41071, 41080],
      dtype=int64)

### The number of missing municipality names has been reduced from 4487 to 3519. Next steps:
- Valencia, Girona, Madrid, Barcelona, Málaga and Sevilla --> take municipality from "province" column
- Euskadi, Mallorca, Menorca --> take municipality from "geo_location" column (separate by comma and take the -4 position)

In [36]:
# complete_address_1_2.loc[complete_address_1_2["municipio_nombre"].isna(), "municipio_nombre"] = \
#     complete_address_1_2.loc[complete_address_1_2["municipio_nombre"].isna(), "neighbourhood"]

In [37]:
mun_1 = ["Valencia", "Girona", "Madrid", "Barcelona", "Málaga", "Sevilla"]
mun_2 = ["Euskadi", "Mallorca", "Menorca"]

In [38]:
df_concat3 = complete_address_1_2[complete_address_1_2["municipio_nombre"].isna()]
df_concat3

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98399,Valencia,39682770,LA PETXINA,39.47706,-0.39169,"Passeig de la Petxina, la Petxina, Extramurs, ...",16015,NaN
98400,Valencia,42531886,ARRANCAPINS,39.46082,-0.38241,"Arrancapins, Extramurs, València, Comarca de V...",0,NaN
98405,Valencia,48050433,LA PETXINA,39.47682,-0.39346,"Estadi del Túria, Avinguda de Campanar, Campan...",16015,NaN
98407,Valencia,47828175,LA RAIOSA,39.45942,-0.38671,"la Raïosa, Jesús, València, Comarca de Valènci...",0,NaN
98409,Valencia,49697009,LA XEREA,39.47470,-0.36992,"la Xerea, Ciutat Vella, València, Comarca de V...",0,NaN
...,...,...,...,...,...,...,...,...
102872,Valencia,34596349,EL CARME,39.47956,-0.37731,"Plaça de l'Autor, el Carme, Ciutat Vella, Valè...",0,NaN
102873,Valencia,36510524,LA SEU,39.47628,-0.37443,"Plaça de Dècim Juni Brut Cònsol Romà, la Seu, ...",0,NaN
102874,Valencia,37206278,EL CALVARI,39.48659,-0.39257,"Carrer de l'Esperantista Hernández Lahuerta, e...",16015,NaN
102877,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN
102880,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN

In [39]:
# Region 1

reg_1 = df_concat3[df_concat3["province"].isin(mun_1)]
reg_1

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98399,Valencia,39682770,LA PETXINA,39.47706,-0.39169,"Passeig de la Petxina, la Petxina, Extramurs, ...",16015,NaN
98400,Valencia,42531886,ARRANCAPINS,39.46082,-0.38241,"Arrancapins, Extramurs, València, Comarca de V...",0,NaN
98405,Valencia,48050433,LA PETXINA,39.47682,-0.39346,"Estadi del Túria, Avinguda de Campanar, Campan...",16015,NaN
98407,Valencia,47828175,LA RAIOSA,39.45942,-0.38671,"la Raïosa, Jesús, València, Comarca de Valènci...",0,NaN
98409,Valencia,49697009,LA XEREA,39.47470,-0.36992,"la Xerea, Ciutat Vella, València, Comarca de V...",0,NaN
...,...,...,...,...,...,...,...,...
102872,Valencia,34596349,EL CARME,39.47956,-0.37731,"Plaça de l'Autor, el Carme, Ciutat Vella, Valè...",0,NaN
102873,Valencia,36510524,LA SEU,39.47628,-0.37443,"Plaça de Dècim Juni Brut Cònsol Romà, la Seu, ...",0,NaN
102874,Valencia,37206278,EL CALVARI,39.48659,-0.39257,"Carrer de l'Esperantista Hernández Lahuerta, e...",16015,NaN
102877,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,NaN
102880,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,NaN

In [40]:
reg_1["municipio_nombre"] = reg_1["province"]
reg_1

C:\Users\Selvie\AppData\Local\Temp\ipykernel_34796\613528296.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reg_1["municipio_nombre"] = reg_1["province"]

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98399,Valencia,39682770,LA PETXINA,39.47706,-0.39169,"Passeig de la Petxina, la Petxina, Extramurs, ...",16015,Valencia
98400,Valencia,42531886,ARRANCAPINS,39.46082,-0.38241,"Arrancapins, Extramurs, València, Comarca de V...",0,Valencia
98405,Valencia,48050433,LA PETXINA,39.47682,-0.39346,"Estadi del Túria, Avinguda de Campanar, Campan...",16015,Valencia
98407,Valencia,47828175,LA RAIOSA,39.45942,-0.38671,"la Raïosa, Jesús, València, Comarca de Valènci...",0,Valencia
98409,Valencia,49697009,LA XEREA,39.47470,-0.36992,"la Xerea, Ciutat Vella, València, Comarca de V...",0,Valencia
...,...,...,...,...,...,...,...,...
102872,Valencia,34596349,EL CARME,39.47956,-0.37731,"Plaça de l'Autor, el Carme, Ciutat Vella, Valè...",0,Valencia
102873,Valencia,36510524,LA SEU,39.47628,-0.37443,"Plaça de Dècim Juni Brut Cònsol Romà, la Seu, ...",0,Valencia
102874,Valencia,37206278,EL CALVARI,39.48659,-0.39257,"Carrer de l'Esperantista Hernández Lahuerta, e...",16015,Valencia
102877,Valencia,37519796,CABANYAL-CANYAMELAR,39.46905,-0.33094,"Plaça del Doctor Llorenç de la Flor, Canyamela...",0,Valencia
102880,Valencia,41497666,EL BOTANIC,39.47597,-0.38461,"Plaça de Maria Beneyto Escriptora, el Botànic,...",0,Valencia

In [41]:
# Region 2

reg_2 = df_concat3[df_concat3["province"].isin(mun_2)]
reg_2

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98482,Euskadi,341691,Bilbao,43.26317,-2.94752,"Garellano, Basurtu-Zorrotza, Bilbao, Bizkaia, ...",0,NaN
98486,Euskadi,1810475,Karrantza Harana,43.21736,-3.33746,"Barrio Cezura, Cezura, Karrantza Harana / Vall...",0,NaN
98487,Euskadi,740932,Bilbao,43.26914,-2.92880,"Tristán de Leguizamón 5, Calle Tristán de Legu...",48071,NaN
98488,Euskadi,1810503,Karrantza Harana,43.22128,-3.33348,"Barrio Cezura, Cezura, Karrantza Harana / Vall...",0,NaN
98490,Euskadi,3448220,Bilbao,43.26066,-2.92967,"Sercotel Ayala, Calle Canciller Ayala / Aiala ...",1232,NaN
...,...,...,...,...,...,...,...,...
102556,Menorca,1230705,Ciutadella de Menorca,39.92834,3.83228,"Via Circumval·lació, Cap d'Artrutx, Cala en Bo...",0,NaN
102557,Menorca,1441001,Ciutadella de Menorca,39.92807,3.84113,"Sol Falcó All Inclusive, Carrer de sa Rosa des...",0,NaN
102558,Menorca,1565297,Es Mercadal,40.03285,4.19082,"s'Arenal d'en Castell, es Mercadal, Menorca, I...",0,NaN
102559,Menorca,1627620,Ciutadella de Menorca,39.99866,3.82601,"Carrer de Cala en Busquets, Son Oleo, Ciutadel...",7060,NaN
102560,Menorca,2270324,Ciutadella de Menorca,39.98588,3.84455,"Carrer de s'Abatzer, Santandria, Ciutadella, M...",7602,NaN

In [42]:
reg_2["municipio_nombre"] = reg_2["neighbourhood"]
reg_2

C:\Users\Selvie\AppData\Local\Temp\ipykernel_34796\798989276.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reg_2["municipio_nombre"] = reg_2["neighbourhood"]

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98482,Euskadi,341691,Bilbao,43.26317,-2.94752,"Garellano, Basurtu-Zorrotza, Bilbao, Bizkaia, ...",0,Bilbao
98486,Euskadi,1810475,Karrantza Harana,43.21736,-3.33746,"Barrio Cezura, Cezura, Karrantza Harana / Vall...",0,Karrantza Harana
98487,Euskadi,740932,Bilbao,43.26914,-2.92880,"Tristán de Leguizamón 5, Calle Tristán de Legu...",48071,Bilbao
98488,Euskadi,1810503,Karrantza Harana,43.22128,-3.33348,"Barrio Cezura, Cezura, Karrantza Harana / Vall...",0,Karrantza Harana
98490,Euskadi,3448220,Bilbao,43.26066,-2.92967,"Sercotel Ayala, Calle Canciller Ayala / Aiala ...",1232,Bilbao
...,...,...,...,...,...,...,...,...
102556,Menorca,1230705,Ciutadella de Menorca,39.92834,3.83228,"Via Circumval·lació, Cap d'Artrutx, Cala en Bo...",0,Ciutadella de Menorca
102557,Menorca,1441001,Ciutadella de Menorca,39.92807,3.84113,"Sol Falcó All Inclusive, Carrer de sa Rosa des...",0,Ciutadella de Menorca
102558,Menorca,1565297,Es Mercadal,40.03285,4.19082,"s'Arenal d'en Castell, es Mercadal, Menorca, I...",0,Es Mercadal
102559,Menorca,1627620,Ciutadella de Menorca,39.99866,3.82601,"Carrer de Cala en Busquets, Son Oleo, Ciutadel...",7060,Ciutadella de Menorca
102560,Menorca,2270324,Ciutadella de Menorca,39.98588,3.84455,"Carrer de s'Abatzer, Santandria, Ciutadella, M...",7602,Ciutadella de Menorca

### Append "reg_1" and "reg_2"

In [43]:
all_regions = pd.concat([reg_1, reg_2], axis=0)
all_regions

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
98399,Valencia,39682770,LA PETXINA,39.47706,-0.39169,"Passeig de la Petxina, la Petxina, Extramurs, ...",16015,Valencia
98400,Valencia,42531886,ARRANCAPINS,39.46082,-0.38241,"Arrancapins, Extramurs, València, Comarca de V...",0,Valencia
98405,Valencia,48050433,LA PETXINA,39.47682,-0.39346,"Estadi del Túria, Avinguda de Campanar, Campan...",16015,Valencia
98407,Valencia,47828175,LA RAIOSA,39.45942,-0.38671,"la Raïosa, Jesús, València, Comarca de Valènci...",0,Valencia
98409,Valencia,49697009,LA XEREA,39.47470,-0.36992,"la Xerea, Ciutat Vella, València, Comarca de V...",0,Valencia
...,...,...,...,...,...,...,...,...
102556,Menorca,1230705,Ciutadella de Menorca,39.92834,3.83228,"Via Circumval·lació, Cap d'Artrutx, Cala en Bo...",0,Ciutadella de Menorca
102557,Menorca,1441001,Ciutadella de Menorca,39.92807,3.84113,"Sol Falcó All Inclusive, Carrer de sa Rosa des...",0,Ciutadella de Menorca
102558,Menorca,1565297,Es Mercadal,40.03285,4.19082,"s'Arenal d'en Castell, es Mercadal, Menorca, I...",0,Es Mercadal
102559,Menorca,1627620,Ciutadella de Menorca,39.99866,3.82601,"Carrer de Cala en Busquets, Son Oleo, Ciutadel...",7060,Ciutadella de Menorca
102560,Menorca,2270324,Ciutadella de Menorca,39.98588,3.84455,"Carrer de s'Abatzer, Santandria, Ciutadella, M...",7602,Ciutadella de Menorca

### Append "complete_address_1_2" with "all_regions"

In [44]:
complete_address_1_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102881 entries, 0 to 102880
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          102881 non-null  object
 1   id                102881 non-null  int64
 2   neighbourhood     102881 non-null  object
 3   latitude          102881 non-null  float64
 4   longitude         102881 non-null  float64
 5   location_geo      102881 non-null  object
 6   zip_code          102881 non-null  int64
 7   municipio_nombre  99362 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 6.3+ MB

In [45]:
all_regions.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3519 entries, 98399 to 102560
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   province          3519 non-null   object
 1   id                3519 non-null   int64
 2   neighbourhood     3519 non-null   object
 3   latitude          3519 non-null   float64
 4   longitude         3519 non-null   float64
 5   location_geo      3519 non-null   object
 6   zip_code          3519 non-null   int64
 7   municipio_nombre  3519 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 247.4+ KB

In [46]:
final_address = pd.concat([complete_address_1_2, all_regions], axis=0)
final_address

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,Barcelona
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,Barcelona
...,...,...,...,...,...,...,...,...
102556,Menorca,1230705,Ciutadella de Menorca,39.92834,3.83228,"Via Circumval·lació, Cap d'Artrutx, Cala en Bo...",0,Ciutadella de Menorca
102557,Menorca,1441001,Ciutadella de Menorca,39.92807,3.84113,"Sol Falcó All Inclusive, Carrer de sa Rosa des...",0,Ciutadella de Menorca
102558,Menorca,1565297,Es Mercadal,40.03285,4.19082,"s'Arenal d'en Castell, es Mercadal, Menorca, I...",0,Es Mercadal
102559,Menorca,1627620,Ciutadella de Menorca,39.99866,3.82601,"Carrer de Cala en Busquets, Son Oleo, Ciutadel...",7060,Ciutadella de Menorca
102560,Menorca,2270324,Ciutadella de Menorca,39.98588,3.84455,"Carrer de s'Abatzer, Santandria, Ciutadella, M...",7602,Ciutadella de Menorca

In [47]:
final_address = final_address.drop_duplicates(subset="id", keep="last")
final_address

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.40556,2.17262,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.41243,2.21975,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.40566,2.17015,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.37978,2.17623,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,Barcelona
4,Barcelona,36763,la Barceloneta,41.38043,2.19094,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,Barcelona
...,...,...,...,...,...,...,...,...
102556,Menorca,1230705,Ciutadella de Menorca,39.92834,3.83228,"Via Circumval·lació, Cap d'Artrutx, Cala en Bo...",0,Ciutadella de Menorca
102557,Menorca,1441001,Ciutadella de Menorca,39.92807,3.84113,"Sol Falcó All Inclusive, Carrer de sa Rosa des...",0,Ciutadella de Menorca
102558,Menorca,1565297,Es Mercadal,40.03285,4.19082,"s'Arenal d'en Castell, es Mercadal, Menorca, I...",0,Es Mercadal
102559,Menorca,1627620,Ciutadella de Menorca,39.99866,3.82601,"Carrer de Cala en Busquets, Son Oleo, Ciutadel...",7060,Ciutadella de Menorca
102560,Menorca,2270324,Ciutadella de Menorca,39.98588,3.84455,"Carrer de s'Abatzer, Santandria, Ciutadella, M...",7602,Ciutadella de Menorca

In [48]:
final_address.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102881 entries, 0 to 102560
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          102881 non-null  object
 1   id                102881 non-null  int64
 2   neighbourhood     102881 non-null  object
 3   latitude          102881 non-null  float64
 4   longitude         102881 non-null  float64
 5   location_geo      102881 non-null  object
 6   zip_code          102881 non-null  int64
 7   municipio_nombre  102881 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 7.1+ MB

In [49]:
final_address.to_csv("Datasets_clean/final_address.csv", encoding="utf-8")

### Breakdown the Euskadi data into 3 provinces: Gipuzkoa, Bizkaia and Araba/Álava

In [50]:
euskadi = final_address[final_address["province"] == "Euskadi"]
euskadi

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
11572,Euskadi,132068,Donostia-San SebastiÃ¡n,43.325200,-1.972090,"San Frantzisko, San Frantzisko kalea, Gros, Do...",20001,Donostia/San Sebastián
11573,Euskadi,1311566,Bilbao,43.258920,-2.918670,"Albergue de Peregrinos Santa Cruz de Begoña, D...",48006,Bilbao
11574,Euskadi,1318286,Bilbao,43.250630,-2.933440,"Avenida Askatasuna / Askatasuna etorbidea, Zab...",48003,Arrigorriaga
11575,Euskadi,309802,Donostia-San SebastiÃ¡n,43.315820,-2.003940,"Villa Izurun, 6, Kristina Infantaren kalea, On...",20008,Donostia/San Sebastián
11576,Euskadi,2718467,Mutriku,43.307630,-2.385350,"13, Atxitxin kalea, Mutriku, Debabarrena, Gipu...",20830,Mutriku
...,...,...,...,...,...,...,...,...
98824,Euskadi,737402965901494731,Donostia-San SebastiÃ¡n,43.317520,-1.985770,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
98825,Euskadi,737593248707994240,Donostia-San SebastiÃ¡n,43.316770,-1.986840,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
98827,Euskadi,741039679220425988,Bilbao,43.260650,-2.927780,"Bilbao-Abando, Calle Padre Lojendio / Aita Loj...",1232,Bilbao
98832,Euskadi,753420933264309930,Bilbao,43.269700,-2.927870,"Calle Mandobide / Mandobide kalea, Castaños, U...",48071,Bilbao
98834,Euskadi,756485500251705924,Kanpezu,42.716698,-2.367049,"Oteo, Campezo/Kanpezu, Montaña Alavesa/Arabako...",0,Kanpezu

In [51]:
def classify_province(address):
    if 'Gipuzkoa' in address:
        return 'Gipuzkoa'
    elif 'Bizkaia' in address:
        return 'Bizkaia'
    elif 'Araba/Álava' in address:
        return 'Araba/Álava'
    elif 'Cantabria' in address:
        return 'Cantabria'
    elif 'La Rioja' in address:
        return 'La Rioja'
    else:
        return 'Gipuzkoa'

In [52]:
euskadi['province'] = euskadi['location_geo'].apply(classify_province)
euskadi

C:\Users\Selvie\AppData\Local\Temp\ipykernel_34796\1434420014.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euskadi['province'] = euskadi['location_geo'].apply(classify_province)

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
11572,Gipuzkoa,132068,Donostia-San SebastiÃ¡n,43.325200,-1.972090,"San Frantzisko, San Frantzisko kalea, Gros, Do...",20001,Donostia/San Sebastián
11573,Bizkaia,1311566,Bilbao,43.258920,-2.918670,"Albergue de Peregrinos Santa Cruz de Begoña, D...",48006,Bilbao
11574,Bizkaia,1318286,Bilbao,43.250630,-2.933440,"Avenida Askatasuna / Askatasuna etorbidea, Zab...",48003,Arrigorriaga
11575,Gipuzkoa,309802,Donostia-San SebastiÃ¡n,43.315820,-2.003940,"Villa Izurun, 6, Kristina Infantaren kalea, On...",20008,Donostia/San Sebastián
11576,Gipuzkoa,2718467,Mutriku,43.307630,-2.385350,"13, Atxitxin kalea, Mutriku, Debabarrena, Gipu...",20830,Mutriku
...,...,...,...,...,...,...,...,...
98824,Gipuzkoa,737402965901494731,Donostia-San SebastiÃ¡n,43.317520,-1.985770,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
98825,Gipuzkoa,737593248707994240,Donostia-San SebastiÃ¡n,43.316770,-1.986840,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
98827,Bizkaia,741039679220425988,Bilbao,43.260650,-2.927780,"Bilbao-Abando, Calle Padre Lojendio / Aita Loj...",1232,Bilbao
98832,Bizkaia,753420933264309930,Bilbao,43.269700,-2.927870,"Calle Mandobide / Mandobide kalea, Castaños, U...",48071,Bilbao
98834,Araba/Álava,756485500251705924,Kanpezu,42.716698,-2.367049,"Oteo, Campezo/Kanpezu, Montaña Alavesa/Arabako...",0,Kanpezu

In [53]:
euskadi["province"].unique()

array(['Gipuzkoa', 'Bizkaia', 'Araba/Álava', 'Cantabria', 'La Rioja'],
      dtype=object)

### In order to update the Euskadi provinces, append the "euskadi" table with the "final_address" table

In [54]:
final_address = pd.concat([final_address, euskadi], axis=0)
final_address

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.405560,2.172620,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.412430,2.219750,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.405660,2.170150,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.379780,2.176230,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,Barcelona
4,Barcelona,36763,la Barceloneta,41.380430,2.190940,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,Barcelona
...,...,...,...,...,...,...,...,...
98824,Gipuzkoa,737402965901494731,Donostia-San SebastiÃ¡n,43.317520,-1.985770,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
98825,Gipuzkoa,737593248707994240,Donostia-San SebastiÃ¡n,43.316770,-1.986840,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
98827,Bizkaia,741039679220425988,Bilbao,43.260650,-2.927780,"Bilbao-Abando, Calle Padre Lojendio / Aita Loj...",1232,Bilbao
98832,Bizkaia,753420933264309930,Bilbao,43.269700,-2.927870,"Calle Mandobide / Mandobide kalea, Castaños, U...",48071,Bilbao
98834,Araba/Álava,756485500251705924,Kanpezu,42.716698,-2.367049,"Oteo, Campezo/Kanpezu, Montaña Alavesa/Arabako...",0,Kanpezu

In [55]:
final_address = final_address.drop_duplicates(subset="id", keep="last")
final_address = final_address.reset_index()
final_address

,index,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
0,0,Barcelona,18674,la Sagrada Família,41.405560,2.172620,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,Barcelona
1,1,Barcelona,23197,el Besòs i el Maresme,41.412430,2.219750,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,Barcelona
2,2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.405660,2.170150,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,Barcelona
3,3,Barcelona,34981,el Barri Gòtic,41.379780,2.176230,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,Barcelona
4,4,Barcelona,36763,la Barceloneta,41.380430,2.190940,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,Barcelona
...,...,...,...,...,...,...,...,...,...
102876,98824,Gipuzkoa,737402965901494731,Donostia-San SebastiÃ¡n,43.317520,-1.985770,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
102877,98825,Gipuzkoa,737593248707994240,Donostia-San SebastiÃ¡n,43.316770,-1.986840,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
102878,98827,Bizkaia,741039679220425988,Bilbao,43.260650,-2.927780,"Bilbao-Abando, Calle Padre Lojendio / Aita Loj...",1232,Bilbao
102879,98832,Bizkaia,753420933264309930,Bilbao,43.269700,-2.927870,"Calle Mandobide / Mandobide kalea, Castaños, U...",48071,Bilbao
102880,98834,Araba/Álava,756485500251705924,Kanpezu,42.716698,-2.367049,"Oteo, Campezo/Kanpezu, Montaña Alavesa/Arabako...",0,Kanpezu

In [56]:
final_address = final_address.drop("index", axis=1)
final_address

,province,id,neighbourhood,latitude,longitude,location_geo,zip_code,municipio_nombre
0,Barcelona,18674,la Sagrada Família,41.405560,2.172620,"277, Carrer de la Marina, el Baix Guinardó, Ho...",8025,Barcelona
1,Barcelona,23197,el Besòs i el Maresme,41.412430,2.219750,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",8019,Barcelona
2,Barcelona,32711,el Camp d'en Grassot i Gràcia Nova,41.405660,2.170150,"365, Carrer de Sardenya, el Camp d'en Grassot ...",8001,Barcelona
3,Barcelona,34981,el Barri Gòtic,41.379780,2.176230,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",8002,Barcelona
4,Barcelona,36763,la Barceloneta,41.380430,2.190940,"El Forat, Carrer de Cermeño, la Barceloneta, C...",8001,Barcelona
...,...,...,...,...,...,...,...,...
102876,Gipuzkoa,737402965901494731,Donostia-San SebastiÃ¡n,43.317520,-1.985770,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
102877,Gipuzkoa,737593248707994240,Donostia-San SebastiÃ¡n,43.316770,-1.986840,"Kontxa pasealekua - Paseo de la Concha, Gune E...",0,Donostia-San SebastiÃ¡n
102878,Bizkaia,741039679220425988,Bilbao,43.260650,-2.927780,"Bilbao-Abando, Calle Padre Lojendio / Aita Loj...",1232,Bilbao
102879,Bizkaia,753420933264309930,Bilbao,43.269700,-2.927870,"Calle Mandobide / Mandobide kalea, Castaños, U...",48071,Bilbao
102880,Araba/Álava,756485500251705924,Kanpezu,42.716698,-2.367049,"Oteo, Campezo/Kanpezu, Montaña Alavesa/Arabako...",0,Kanpezu

In [57]:
final_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102881 entries, 0 to 102880
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          102881 non-null  object
 1   id                102881 non-null  int64
 2   neighbourhood     102881 non-null  object
 3   latitude          102881 non-null  float64
 4   longitude         102881 non-null  float64
 5   location_geo      102881 non-null  object
 6   zip_code          102881 non-null  int64
 7   municipio_nombre  102881 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 6.3+ MB

In [58]:
final_address["province"].unique()

array(['Barcelona', 'Valencia', 'Girona', 'Madrid', 'Málaga', 'Mallorca',
       'Menorca', 'Sevilla', 'Gipuzkoa', 'Bizkaia', 'Araba/Álava',
       'Cantabria', 'La Rioja'], dtype=object)

## Classify the states/ comunidad autónoma

In [59]:
def classify_state(province):
    if "Barcelona" in province:
        return "Cataluña"
    elif "Valencia" in province:
        return "Comunidad Valenciana"
    elif "Girona" in province:
        return "Cataluña"
    elif "Madrid" in province:
        return "Comunidad de Madrid"
    elif "Málaga" in province:
        return "Andalucía"
    elif "Mallorca" in province:
        return "Islas Baleares"
    elif "Menorca" in province:
        return "Islas Baleares"
    elif "Sevilla" in province:
        return "Andalucía"
    elif "Gipuzkoa" in province:
        return "País Vasco"
    elif "Bizkaia" in province:
        return "País Vasco"
    elif "Araba/Álava" in province:
        return "País Vasco"
    elif "Cantabria" in province:
        return "Cantabria"
    elif "La Rioja" in province:
        return "La Rioja"

In [60]:
final_address["state"] = final_address["province"].apply(classify_state)
final_address = final_address[["id", "latitude", "longitude", "location_geo", "state", 
                               "province", "municipio_nombre", "zip_code"]]
final_address

,id,latitude,longitude,location_geo,state,province,municipio_nombre,zip_code
0,18674,41.405560,2.172620,"277, Carrer de la Marina, el Baix Guinardó, Ho...",Cataluña,Barcelona,Barcelona,8025
1,23197,41.412430,2.219750,"Diagonal Zero Zero, 6, Rambla de Prim, el Besò...",Cataluña,Barcelona,Barcelona,8019
2,32711,41.405660,2.170150,"365, Carrer de Sardenya, el Camp d'en Grassot ...",Cataluña,Barcelona,Barcelona,8001
3,34981,41.379780,2.176230,"7, Carrer del Vidre, el Gòtic, Ciutat Vella, B...",Cataluña,Barcelona,Barcelona,8002
4,36763,41.380430,2.190940,"El Forat, Carrer de Cermeño, la Barceloneta, C...",Cataluña,Barcelona,Barcelona,8001
...,...,...,...,...,...,...,...,...
102876,737402965901494731,43.317520,-1.985770,"Kontxa pasealekua - Paseo de la Concha, Gune E...",País Vasco,Gipuzkoa,Donostia-San SebastiÃ¡n,0
102877,737593248707994240,43.316770,-1.986840,"Kontxa pasealekua - Paseo de la Concha, Gune E...",País Vasco,Gipuzkoa,Donostia-San SebastiÃ¡n,0
102878,741039679220425988,43.260650,-2.927780,"Bilbao-Abando, Calle Padre Lojendio / Aita Loj...",País Vasco,Bizkaia,Bilbao,1232
102879,753420933264309930,43.269700,-2.927870,"Calle Mandobide / Mandobide kalea, Castaños, U...",País Vasco,Bizkaia,Bilbao,48071
102880,756485500251705924,42.716698,-2.367049,"Oteo, Campezo/Kanpezu, Montaña Alavesa/Arabako...",País Vasco,Araba/Álava,Kanpezu,0

In [61]:
final_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102881 entries, 0 to 102880
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                102881 non-null  int64
 1   latitude          102881 non-null  float64
 2   longitude         102881 non-null  float64
 3   location_geo      102881 non-null  object
 4   state             102881 non-null  object
 5   province          102881 non-null  object
 6   municipio_nombre  102881 non-null  object
 7   zip_code          102881 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 6.3+ MB

In [62]:
final_address.to_csv("Datasets_clean/final_address.csv", encoding="utf-8")

## Property Listing 1

In [81]:
listing_es = pd.read_csv("Datasets_clean/listing_es.csv", encoding="utf-8")
listing_es.head()

,Unnamed: 0,timestamp_date,city,id,name,host_id,host_name,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,0,2022-12-11,Barcelona,18674,Huge flat for 8 people close to Sagrada Familia,71615,Mireia And Maria,41.40556,2.17262,Entire home/apt,129,1,33,2022-10-07,0.28,20,264,11,HUTB-002062
1,1,2022-12-11,Barcelona,23197,"Forum CCIB DeLuxe, Spacious, Elegant ,Christmas",90417,Etain (Marnie),41.41243,2.21975,Entire home/apt,195,4,65,2022-10-23,0.45,2,255,12,HUTB005057
2,2,2022-12-11,Barcelona,32711,Sagrada Familia area - Còrsega 1,135703,Nick,41.40566,2.17015,Entire home/apt,73,2,83,2022-12-09,0.60,3,276,20,HUTB-001722
3,3,2022-12-11,Barcelona,34981,VIDRE HOME PLAZA REAL on LAS RAMBLAS,73163,Andres,41.37978,2.17623,Entire home/apt,174,5,190,2022-11-19,1.28,1,139,30,HUTB-001506
4,4,2022-12-11,Barcelona,36763,In front of the beach,158596,Ester,41.38043,2.19094,Private room,36,31,104,2022-10-05,0.76,1,259,19,NaN

In [82]:
listing_es = listing_es.drop(["Unnamed: 0", "city"], axis=1)

In [83]:
listing_es.head()

,timestamp_date,id,name,host_id,host_name,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2022-12-11,18674,Huge flat for 8 people close to Sagrada Familia,71615,Mireia And Maria,41.40556,2.17262,Entire home/apt,129,1,33,2022-10-07,0.28,20,264,11,HUTB-002062
1,2022-12-11,23197,"Forum CCIB DeLuxe, Spacious, Elegant ,Christmas",90417,Etain (Marnie),41.41243,2.21975,Entire home/apt,195,4,65,2022-10-23,0.45,2,255,12,HUTB005057
2,2022-12-11,32711,Sagrada Familia area - Còrsega 1,135703,Nick,41.40566,2.17015,Entire home/apt,73,2,83,2022-12-09,0.60,3,276,20,HUTB-001722
3,2022-12-11,34981,VIDRE HOME PLAZA REAL on LAS RAMBLAS,73163,Andres,41.37978,2.17623,Entire home/apt,174,5,190,2022-11-19,1.28,1,139,30,HUTB-001506
4,2022-12-11,36763,In front of the beach,158596,Ester,41.38043,2.19094,Private room,36,31,104,2022-10-05,0.76,1,259,19,NaN

In [84]:
listing_es.to_csv("Datasets_analysis/listing_es.csv", encoding="utf-8")

## Property Listing 2 (Rating)

In [3]:
rating_es = pd.read_csv("Datasets_clean/listing_es2.csv", encoding="utf-8")
rating_es.head()

,Unnamed: 0,timestamp_date,city,id,listing_url,scrape_id,last_scraped,source,name,description,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,2022-12-11,Barcelona,18674,https://www.airbnb.com/rooms/18674,20221211170659,2022-12-11,city scrape,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,...,4.69,4.81,4.28,HUTB-002062,t,20,20,0,0,0.28
1,1,2022-12-11,Barcelona,124342,https://www.airbnb.com/rooms/124342,20221211170659,2022-12-11,city scrape,BORN CENTRICO / MUSEO PICASSO / 10 min to BEACH,Double room at El Born / MONTHLY RENTAL & DAY...,...,4.88,4.95,4.49,HUTB-123456,f,1,0,1,0,0.56
2,2,2022-12-11,Barcelona,128463,https://www.airbnb.com/rooms/128463,20221211170659,2022-12-12,city scrape,Private Suite in residential area!!,My House is located in the quiet district of S...,...,4.90,4.73,4.82,HUTB-012603,t,1,0,1,0,2.53
3,3,2022-12-11,Barcelona,130227,https://www.airbnb.com/rooms/130227,20221211170659,2022-12-11,city scrape,Spacious Room with Pool and Terrace,Just 5 minutes’ walk from the beach in the San...,...,4.78,4.73,4.64,Exempt,f,1,0,1,0,1.24
4,4,2022-12-11,Barcelona,135513,https://www.airbnb.com/rooms/135513,20221211170659,2022-12-11,city scrape,APARTMENT AT RAMBLA POBLE NOU AND BEACH,AMAZING APARTMENT AT RAMBLA OF POBLE NOU ; ONL...,...,4.80,4.83,4.56,NaN,f,2,2,0,0,0.96

In [4]:
rating_es = rating_es.drop(["Unnamed: 0", "city"], axis=1)

In [5]:
rating_es.head()

,timestamp_date,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2022-12-11,18674,https://www.airbnb.com/rooms/18674,20221211170659,2022-12-11,city scrape,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,Apartment in Barcelona located in the heart of...,https://a0.muscache.com/pictures/13031453/413c...,...,4.69,4.81,4.28,HUTB-002062,t,20,20,0,0,0.28
1,2022-12-11,124342,https://www.airbnb.com/rooms/124342,20221211170659,2022-12-11,city scrape,BORN CENTRICO / MUSEO PICASSO / 10 min to BEACH,Double room at El Born / MONTHLY RENTAL & DAY...,NaN,https://a0.muscache.com/pictures/6058611/f5160...,...,4.88,4.95,4.49,HUTB-123456,f,1,0,1,0,0.56
2,2022-12-11,128463,https://www.airbnb.com/rooms/128463,20221211170659,2022-12-12,city scrape,Private Suite in residential area!!,My House is located in the quiet district of S...,You live in a typical Spanish district with no...,https://a0.muscache.com/pictures/855084/c71b65...,...,4.90,4.73,4.82,HUTB-012603,t,1,0,1,0,2.53
3,2022-12-11,130227,https://www.airbnb.com/rooms/130227,20221211170659,2022-12-11,city scrape,Spacious Room with Pool and Terrace,Just 5 minutes’ walk from the beach in the San...,NaN,https://a0.muscache.com/pictures/14284828/d2ea...,...,4.78,4.73,4.64,Exempt,f,1,0,1,0,1.24
4,2022-12-11,135513,https://www.airbnb.com/rooms/135513,20221211170659,2022-12-11,city scrape,APARTMENT AT RAMBLA POBLE NOU AND BEACH,AMAZING APARTMENT AT RAMBLA OF POBLE NOU ; ONL...,NaN,https://a0.muscache.com/pictures/9578738/40581...,...,4.80,4.83,4.56,NaN,f,2,2,0,0,0.96

In [6]:
rating_es[['property_type', 'room_type', 'accommodates', 'bedrooms', 'beds']]

,property_type,room_type,accommodates,bedrooms,beds
0,Entire rental unit,Entire home/apt,8,3.0,6.0
1,Private room in rental unit,Private room,2,1.0,1.0
2,Private room in rental unit,Private room,2,1.0,1.0
3,Private room in condo,Private room,2,3.0,1.0
4,Entire rental unit,Entire home/apt,5,2.0,3.0
...,...,...,...,...,...
895,Entire rental unit,Entire home/apt,2,NaN,1.0
896,Entire rental unit,Entire home/apt,4,2.0,3.0
897,Entire rental unit,Entire home/apt,6,2.0,4.0
898,Entire rental unit,Entire home/apt,6,3.0,4.0
899,Private room in condo,Private room,2,1.0,1.0

In [7]:
rating_es["number_of_reviews"]

0       33
1       79
2      347
3      130
4      131
      ...
895    285
896    359
897      6
898     45
899     91
Name: number_of_reviews, Length: 900, dtype: int64

In [8]:
rating_es[['review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable']]

,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,4.31,4.41,4.63,4.78,4.69,4.81,4.28,t
1,4.56,4.14,4.61,4.87,4.88,4.95,4.49,f
2,4.87,4.91,4.94,4.94,4.90,4.73,4.82,t
3,4.72,4.84,4.92,4.88,4.78,4.73,4.64,f
4,4.64,4.74,4.68,4.69,4.80,4.83,4.56,f
...,...,...,...,...,...,...,...,...
895,4.52,4.70,4.57,4.85,4.82,4.88,4.57,f
896,4.47,4.66,4.56,4.79,4.76,4.90,4.61,f
897,4.67,4.83,4.83,4.83,4.83,4.83,4.83,f
898,4.67,4.62,4.64,4.82,4.84,4.67,4.58,f
899,4.81,4.85,4.85,4.88,4.89,4.94,4.76,f

In [9]:
rating_es.columns

Index(['timestamp_date', 'id', 'listing_url', 'scrape_id', 'last_scraped',
       'source', 'name', 'description', 'neighborhood_overview', 'picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [10]:
rating_es = rating_es[["id", "name", "description", "neighborhood_overview", "host_id", "host_response_time", "host_response_rate",
                       "host_acceptance_rate", "host_is_superhost", "host_has_profile_pic", "host_identity_verified",
                       "property_type", "room_type", "accommodates", "bedrooms", "beds", "price", "minimum_nights", "maximum_nights",
                       "number_of_reviews", "review_scores_rating", "review_scores_accuracy", "review_scores_cleanliness", 
                       "review_scores_checkin", "review_scores_communication", "review_scores_location","review_scores_value", 
                       "instant_bookable"]]
rating_es.head()

,id,name,description,neighborhood_overview,host_id,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_has_profile_pic,...,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,18674,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,Apartment in Barcelona located in the heart of...,71615,within an hour,100%,94%,f,t,...,1125,33,4.31,4.41,4.63,4.78,4.69,4.81,4.28,t
1,124342,BORN CENTRICO / MUSEO PICASSO / 10 min to BEACH,Double room at El Born / MONTHLY RENTAL & DAY...,NaN,548084,within a day,60%,43%,f,t,...,365,79,4.56,4.14,4.61,4.87,4.88,4.95,4.49,f
2,128463,Private Suite in residential area!!,My House is located in the quiet district of S...,You live in a typical Spanish district with no...,635253,within an hour,100%,100%,t,t,...,1125,347,4.87,4.91,4.94,4.94,4.90,4.73,4.82,t
3,130227,Spacious Room with Pool and Terrace,Just 5 minutes’ walk from the beach in the San...,NaN,641496,NaN,NaN,100%,f,t,...,31,130,4.72,4.84,4.92,4.88,4.78,4.73,4.64,f
4,135513,APARTMENT AT RAMBLA POBLE NOU AND BEACH,AMAZING APARTMENT AT RAMBLA OF POBLE NOU ; ONL...,NaN,664196,within an hour,83%,18%,f,t,...,365,131,4.64,4.74,4.68,4.69,4.80,4.83,4.56,f

In [11]:
rating_es.to_csv("Datasets_analysis/rating_es.csv", encoding="utf-8")

In [12]:
rating_es.to_csv("Datasets_PowerBI/rating_es.csv", encoding="utf-8")

## Property Availability Calendar

In [92]:
cal_es = pd.read_csv("Datasets_clean\calendar_es.csv", encoding="utf-8")
cal_es.head()

,Unnamed: 0,timestamp_date,city,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,0,2022-12-11,Barcelona,18674,2022-12-11,f,$111.00,$111.00,2,1125
1,1,2022-12-11,Barcelona,18674,2022-12-12,f,$111.00,$111.00,2,1125
2,2,2022-12-11,Barcelona,18674,2022-12-13,t,$175.00,$175.00,1,1125
3,3,2022-12-11,Barcelona,18674,2022-12-14,f,$111.00,$111.00,2,1125
4,4,2022-12-11,Barcelona,18674,2022-12-15,f,$111.00,$111.00,2,1125

In [94]:
cal_es = cal_es.drop(["Unnamed: 0", "city"], axis=1)

In [95]:
cal_es.head()

,timestamp_date,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2022-12-11,18674,2022-12-11,f,$111.00,$111.00,2,1125
1,2022-12-11,18674,2022-12-12,f,$111.00,$111.00,2,1125
2,2022-12-11,18674,2022-12-13,t,$175.00,$175.00,1,1125
3,2022-12-11,18674,2022-12-14,f,$111.00,$111.00,2,1125
4,2022-12-11,18674,2022-12-15,f,$111.00,$111.00,2,1125

In [98]:
cal_es.to_csv("Datasets_analysis/calendar_es.csv", encoding="utf-8")

## Property Review

In [104]:
rev_es = pd.read_csv("Datasets_clean/review_es.csv", encoding="utf-8")
rev_es.head()

,Unnamed: 0,timestamp_date,city,listing_id,id,date,reviewer_id,reviewer_name,comments
0,0,2022-12-11,Barcelona,18674,4808211,2013-05-27,4841196,Caron,"Great location. Clean, spacious flat. Would re..."
1,1,2022-12-11,Barcelona,18674,10660311,2014-03-02,11600277,Juan Carlos,Mi mejor recomendación para este departamento....
2,2,2022-12-11,Barcelona,18674,41087522,2015-08-04,35231385,Shlomi,"Big apartment, well equipped.\r<br/>Very good ..."
3,3,2022-12-11,Barcelona,18674,81000756,2016-06-20,23223644,Joost,The Check in was fast and flexible. The price ...
4,4,2022-12-11,Barcelona,18674,278588962,2018-06-18,4756672,Marius,Great location and enough space in the apartme...

In [105]:
rev_es = rev_es.drop(["Unnamed: 0", "city"], axis=1)

In [106]:
rev_es.head()

,timestamp_date,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2022-12-11,18674,4808211,2013-05-27,4841196,Caron,"Great location. Clean, spacious flat. Would re..."
1,2022-12-11,18674,10660311,2014-03-02,11600277,Juan Carlos,Mi mejor recomendación para este departamento....
2,2022-12-11,18674,41087522,2015-08-04,35231385,Shlomi,"Big apartment, well equipped.\r<br/>Very good ..."
3,2022-12-11,18674,81000756,2016-06-20,23223644,Joost,The Check in was fast and flexible. The price ...
4,2022-12-11,18674,278588962,2018-06-18,4756672,Marius,Great location and enough space in the apartme...

In [107]:
rev_es.to_csv("Datasets_analysis/review_es.csv", encoding="utf-8")